version: "3.7"
services:
    main:
        build:
            args:
                user: ceiboo
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: cieboo-main
        container_name: ceiboo-main-php
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - bg-ceiboo

    db:
        image: mysql:5.7
        container_name: ceiboo-main-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ceiboo-main-db
            MYSQL_ROOT_PASSWORD: NFt36_XsRTW?aAP
            MYSQL_PASSWORD: ROx9NW?s_Xab34y
            MYSQL_USER: admin
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - bg-ceiboo

    #store cache
    #memcached:
    #    image: memcached
    #    container_name: ceiboo-main-memcached
    #    ports:
    #    - "11211:11211"

    nginx:
        image: nginx:alpine
        container_name: ceiboo-main-nginx
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./:/var/www
            - ./.docker/nginx/:/etc/nginx/conf.d/
        networks:
            - bg-ceiboo

networks:
    bg-ceiboo:
        driver: bridge
